# Hello Creative Coding NYC!

Import what we will use

In [32]:
import os
import numpy as np

from keras.applications import InceptionV3
from keras.applications.inception_v3 import decode_predictions

from keras.preprocessing import image

Use the `Inception3` image recognition model

In [30]:
model = InceptionV3(weights='imagenet',
                    include_top=True,
                    input_shape=(150, 150, 3))

Show the model architecture

In [31]:
model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            (None, 150, 150, 3)  0                                            
__________________________________________________________________________________________________
conv2d_95 (Conv2D)              (None, 74, 74, 32)   864         input_2[0][0]                    
__________________________________________________________________________________________________
batch_normalization_95 (BatchNo (None, 74, 74, 32)   96          conv2d_95[0][0]                  
__________________________________________________________________________________________________
activation_95 (Activation)      (None, 74, 74, 32)   0           batch_normalization_95[0][0]     
__________________________________________________________________________________________________
conv2d_96 

I have several images ready for identifying

In [46]:
images = [
  'panda.jpg', # 0 
  'cat.jpg',   # 1
  'dog.jpg',   # 2
  'bunny.jpg'  # 3
]

Pick an image to identify

In [40]:
image_index = 0

Set correct image path

In [45]:
base_dir = '../../images'
img_path = os.path.join(base_dir, images[image_index])

print('Using:', images[image_index])

Using: panda.jpg


Transform image into tensor

In [44]:
img = image.load_img(img_path, target_size=(150, 150))

img_tensor = image.img_to_array(img)
img_tensor = np.expand_dims(img_tensor, axis=0)
img_tensor /= 255.

See what the tensor looks like

In [36]:
img_tensor.shape

In [47]:
img_tensor

array([[[[ 0.29411766,  0.27843139,  0.27450982],
         [ 0.29803923,  0.29411766,  0.28627452],
         [ 0.29803923,  0.29411766,  0.28627452],
         ..., 
         [ 0.69803923,  0.81960785,  0.90196079],
         [ 0.69411767,  0.81568629,  0.89803922],
         [ 0.69411767,  0.81568629,  0.89803922]],

        [[ 0.3764706 ,  0.36078432,  0.35686275],
         [ 0.36470589,  0.34901962,  0.34509805],
         [ 0.36470589,  0.34901962,  0.34509805],
         ..., 
         [ 0.70588237,  0.82745099,  0.90980393],
         [ 0.69803923,  0.81960785,  0.90196079],
         [ 0.69803923,  0.81960785,  0.90196079]],

        [[ 0.3764706 ,  0.36078432,  0.35686275],
         [ 0.36470589,  0.34901962,  0.34509805],
         [ 0.36470589,  0.34901962,  0.34509805],
         ..., 
         [ 0.70588237,  0.82745099,  0.90980393],
         [ 0.69803923,  0.81960785,  0.90196079],
         [ 0.69803923,  0.81960785,  0.90196079]],

        ..., 
        [[ 0.37254903,  0.54509807,

### Make the prediction

In [37]:
prediction = model.predict(img_tensor)

See what the prediction looks like

In [48]:
prediction

array([[  8.36089141e-19,   1.67770912e-18,   3.54555904e-21,
          7.11034373e-20,   1.86627084e-20,   1.30657068e-19,
          1.14236628e-19,   1.69427885e-23,   9.56902566e-22,
          3.30420354e-23,   2.79593232e-22,   2.05132752e-17,
          1.91238018e-20,   4.31064459e-23,   8.95368406e-20,
          2.63892971e-21,   6.40437933e-20,   8.78253866e-22,
          6.27350659e-23,   5.05377337e-20,   1.37003566e-21,
          5.03134417e-20,   1.34617950e-20,   3.66261722e-21,
          3.02239560e-23,   5.83612758e-20,   4.74964321e-21,
          1.17551210e-20,   3.85042831e-22,   3.58222681e-20,
          1.67301469e-22,   2.53236175e-20,   1.18049118e-20,
          4.82311664e-20,   5.28615344e-21,   5.74205032e-21,
          5.20375022e-18,   1.60903464e-20,   2.63555201e-19,
          4.67016190e-20,   3.57451432e-20,   1.15502551e-19,
          1.10086417e-19,   8.47413418e-21,   5.92283484e-20,
          4.06716559e-18,   3.34518561e-20,   1.01780665e-19,
        

In [49]:
prediction[0][:20]

array([  8.36089141e-19,   1.67770912e-18,   3.54555904e-21,
         7.11034373e-20,   1.86627084e-20,   1.30657068e-19,
         1.14236628e-19,   1.69427885e-23,   9.56902566e-22,
         3.30420354e-23,   2.79593232e-22,   2.05132752e-17,
         1.91238018e-20,   4.31064459e-23,   8.95368406e-20,
         2.63892971e-21,   6.40437933e-20,   8.78253866e-22,
         6.27350659e-23,   5.05377337e-20], dtype=float32)

Decode the prediction

In [39]:
decode_predictions(prediction, top=3)

[[('n02510455', 'giant_panda', 0.99993658),
  ('n02509815', 'lesser_panda', 6.3436659e-05),
  ('n02132136', 'brown_bear', 6.8793499e-10)]]

Now go back and choose a different image to identify